# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Multica CLI — local agent runtime and management tool for the Multica platform"
  homepage "https://github.com/nullne/multica"
  version "0.2.85"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nullne/multica/releases/download/v0.2.85/multica_darwin_amd64.tar.gz"
      sha256 "80d0593122ba4a9f9b15019a0ae57c5d71af6ec79dac17bf4db08e84837af829"

      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nullne/multica/releases/download/v0.2.85/multica_darwin_arm64.tar.gz"
      sha256 "2356cb95ce569a6a1f9c41509cb8c135d23f1b87c8fb0633a8783dbfabdc6b0f"

      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nullne/multica/releases/download/v0.2.85/multica_linux_amd64.tar.gz"
      sha256 "167f788a8cb28c679a9e48bbd94c66dc9ec7d3a0950669fac6b7c98925e45cce"
      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nullne/multica/releases/download/v0.2.85/multica_linux_arm64.tar.gz"
      sha256 "857f7332a84b1068462262aa990fa2b3afb5b5a9de3ace19156fd41b8de51fbc"
      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
  end
end
