# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Multica CLI — local agent runtime and management tool for the Multica platform"
  homepage "https://github.com/nullne/multica"
  version "0.2.93"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nullne/multica/releases/download/v0.2.93/multica_darwin_amd64.tar.gz"
      sha256 "aa83053551865035c1f1a7999f47d448a200e62270cbe7ec0f28b61bd60d3eb5"

      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nullne/multica/releases/download/v0.2.93/multica_darwin_arm64.tar.gz"
      sha256 "8f97ad28dc00bc91325de544f341ba5e54655f5b05418947f9f066a4033ce43e"

      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nullne/multica/releases/download/v0.2.93/multica_linux_amd64.tar.gz"
      sha256 "d05c8ba39d48afc4f68f0d41284e415fda6f3c0ce03e5c1230dc324cbaa5eacb"
      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nullne/multica/releases/download/v0.2.93/multica_linux_arm64.tar.gz"
      sha256 "0a48f9cfa0c1398c80394c0f9520ca51bd9fdfcdb08489f18a0ce7840e94007c"
      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
  end
end
